### ISSUE TITLE
AI sees into areas its not supposed to see into

### ISSUE THREAD

**Issue by Quantum-M** [OracleStation/OracleStation#1014]
Round ID: 3135.

As a AI, I was able to see into areas that I was not supposed to see into. These included the maintenance tunnels and space, mind that these areas did not have any cameras.

May have to do with 512, and its a big issue balance wise, as AI can see into antag activities in areas they do not have any cameras in.

**Comment by DaveTheHeadcrab** [comment]
Can you replicate this?
Are you sure noone was upgrading your cameras for you?

**Comment by Quantum-M** [comment]
This was near round start, I am certain I was not being given x-ray cameras, and I was not a antag (it was blob round).

**Comment by Quantum-M** [comment]
@DaveTheHeadcrab Tested it in a private server, seems to also happen, I could see way into space outside the station even though cameras don't reach there/there were no cameras in that area.

**Comment by DaveTheHeadcrab** [comment]
Is this happening every round or only on some rounds? Can we point out patterns on the rounds where it is happening if it isn't every round?

**Comment by Quantum-M** [comment]
The round I mentioned, the blob one, was the one after the cult one @ShattForte mentioned.

**Comment by spoonitate** [comment]
After testing this for a few days on live, here's what I found;

1. This bug can occur at round start.
2. The AI is unable to interact with anything cameras cannot see, even if it is visible through the use of this bug.
3. When viewing things through the use of this bug, the AI cannot examine with shift-click, right click, or alt click on turf. They will, however, be able to see the names of objects when the mouse is hovered over it.
4. When jumping from camera networks or tracking crewmembers, some parts of the map are once again obscured by static while others remain visible. How this happens seems to be random, but possibly has something to do with how the client handles information sent by the server.
5. Space can indeed become visible through the use of this bug.
6. This bug seems to only work if there are cameras nearby that would be able to see otherwise obscured tiles, if walls did not exist. 

As far as I can tell, there are no steps to reproduce it reliably. Switching from camera networks to tracking people to freecamming seems to "reroll" the amount of randomly obscured turf. Deconstructing and repairing cameras appears to fix the matter.

**Comment by SamHPurp** [comment]
Everytime you guys have this happen can you please tell us what version of 512 you are using? (512 is only the major release, we need to know the minor release too)

**Comment by Quantum-M** [comment]
I believe the build I am using is the latest (512.1434).

**Comment by spoonitate** [comment]
I was using 512.1432.
