### ISSUE TITLE
IPCs Are Changeling Targets For Their Identity/Leave Objective

### ISSUE THREAD

**Issue by scrubmcnoob** [OracleStation/OracleStation#798]
What it says on the tin

**Comment by Ziiro** [comment]
When you were typing up this issue I took some time to look into how exactly I'd fix this. Here's the problem.

Changelings check for targets using the `find_target()` proc. Which is here.
https://github.com/OracleStation/OracleStation/blob/390c7880679793f9d43e8e700550c1c520ecfdf3/code/game/gamemodes/objective.dm#L36-L46

Here's where it's used.
https://github.com/OracleStation/OracleStation/blob/87874c9431179e2b232b5c5db36393a076543af2/code/game/gamemodes/changeling/changeling.dm#L140-L158

Gears are turning as to how I'd *actually* fix this but I don't see it as too simple because I would have to make another fucking var for "invalid_id_target" or something in the gamemode that is checked when find target is used
