### ISSUE TITLE
Syndicate Comms base supply console won't work

### ISSUE THREAD

**Issue by Mrrpip** [OracleStation/OracleStation#870]
Yep, when i was playing syndicate comms agent today, i checked out the new place, but when i went to the cargo part and used the supply console, it simply displayed "Missing"

**Comment by miniusAreas** [comment]
This is not a bug, rather a possibly exploitable feature. The console says missing because it is not for a cargo shuttle of any kind, it is rather the Nuke Ops shuttle console, except deactivated for prop use. It can be screwed off and back on to re-gain shuttle controls, and can allow traitors to get to the Syndicate Motherbase provided they have a syndicate ID.
